# Generated by Django 5.0.4 on 2024-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='default.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
