# Generated by Django 5.0.4 on 2024-05-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
