# Generated by Django 5.0.4 on 2024-06-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_event_event_type_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('general', 'General'), ('becas', 'Becas'), ('pasantias', 'Pasantías')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
    ]
